.TH TOX-QUICKSTART "1" "August 2019" "Debian" "tox Documentation"
.SH NAME
tox-quickstart \- generate a tox config file for a Python project
.SH SYNOPSIS
\fBtox-quickstart\fP [\fIroot\fP]
.SH DESCRIPTION
.sp
tox-quickstart is helper to quickly generate a \fItox\fP config file for a
given Python project.
.SH OPTIONS
.TP
\fBroot\fR
Custom root directory to write config to. Defaults to current
directory.
.SH "SEE ALSO"
\fBtox\fR(1)
